name: dev_funcproc
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyyaml
  - nibabel
  - joblib
  - scikit-learn
  - click
  - tqdm
  - h5py
  - toml
  - pip:
      - git+https://github.com/nilearn/nilearn.git
      - git+https://github.com/VU-Cog-Sci/prfpy.git
      - git+https://github.com/gjheij/pybest.git
      # - git+https://github.com/gjheij/fmriproc.git
      # - git+https://github.com/gjheij/lazyfmri.git
      - -e .